version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brain_ag
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: brain_ag
      DB_HOST: db         # <-- aqui usamos o nome do serviço do Postgres
      DB_PORT: 5432
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
